name: Wiki home update

on: 
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup variables
        run: echo "myProject=aaa" >> $GITHUB_ENV

      - name: Checkout wiki repo
        uses: actions/checkout@v3
        with:
          repository: '${{ github.repository }}.wiki'
          sparse-checkout: 'Home.md'

      - name: temp1
        run: |
            cat Home.md

      - name: Update project index wiki file
        run: |
          # add project to general index page
          echo "* [${{ env.myProject }}](https://github.com/bromba-noesis/wiki/wiki/${{ env.myProject }})" >> Home.md
          # sort index
          grep -v '^[[:space:]]*$' Home.md | sort > newHome.md
          mv newHome.md Home.md

      - name: Create project wiki files
        run: |
          # create new project index page
          echo "Deployments by environment:" > ${{ env.myProject }}_Home.md
          echo "* [Dev](https://github.com/bromba-noesis/envs-public/wiki/${{ env.myProject }}_Development_deployments)" >> ${{ env.myProject }}_Home.md
          echo "* [Qua](https://github.com/bromba-noesis/envs-public/wiki/${{ env.myProject }}_Quality_deployments)" >> ${{ env.myProject }}_Home.md
          echo "* [Prd](https://github.com/bromba-noesis/envs-public/wiki/${{ env.myProject }}_Production_deployments)" >> ${{ env.myProject }}_Home.md
          # create empty page for each environment 
          echo "-" > ${{ env.myProject }}_Development_deployments.md
          echo "-" > ${{ env.myProject }}_Quality_deployments.md
          echo "-" > ${{ env.myProject }}_Production_deployments.md

      - name: temp2
        run: |
            find .
            cat ${{ env.myProject }}_Home.md
            
      - name: Upload pages to wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: .
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.bromba_noesis_pat_wiki }}
