name: Wiki home update

on: 
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup variables
        run: echo "myProject=bbb" >> $GITHUB_ENV

      - name: Update project wiki files
        uses: DamianReeves/write-file-action@master
        with:
          path: wiki/home.md
          contents: |
            * [${{ env.myProject }}](https://github.com/bromba-noesis/wiki/wiki/${{ env.myProject }})
          write-mode: overwrite

      - name: Upload to wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: wiki/
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.bromba_noesis_pat_wiki }}
