name: Wiki project create

on: 
    workflow_dispatch:
      inputs:
        repoName:
          description: 'New repo name to create wiki on'
          required: true
          type: string

jobs:
  create-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo.wiki
        uses: actions/checkout@v3
        with:
          repository: 'bromba-noesis/${{ inputs.repoName }}.wiki'
          path: 'wiki'
      - name: Create repo pages
        run: |
          # create new wiki index page
          echo "Deployments by environment:" > Home.md
          echo "* [Dev](https://github.com/bromba-noesis/${{ inputs.repoName }}/wiki/Development_Deployments)" >> Home.md
          echo "* [Qua](https://github.com/bromba-noesis/${{ inputs.repoName }}/wiki/Quality_Deployments)" >> Home.md
          echo "* [Prd](https://github.com/bromba-noesis/${{ inputs.repoName }}/wiki/Production_Deployments)" >> Home.md
          # create empty page for each environment 
          echo "-" > Development_Deployments.md
          echo "-" > Quality_Deployments.md
          echo "-" > Production_Deployments.md
          
      - name: Upload pages to wiki
        uses: bromba-noesis/github-wiki-publish-action@v1
        with:
          path: .
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.bromba_noesis_pat_wiki }}
