name: Wiki home update

on: 
    workflow_dispatch:
      inputs:
        projectName:
          description: 'New project name to create'
          required: true
          type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      #- name: Setup variables
      #  run: echo "myProject=bbb" >> $GITHUB_ENV

      - name: Checkout wiki.wiki repo
        uses: actions/checkout@v3
        with:
          repository: '${{ github.repository }}.wiki'
          sparse-checkout: 'Home.md'

      - name: Update project index page
        run: |
          # add project to general index page
          echo "* [${{ env.projectName }}](https://github.com/bromba-noesis/wiki/wiki/${{ env.projectName }}_Home)" >> Home.md
          # sort index
          grep -v '^[[:space:]]*$' Home.md | sort > newHome.md
          mv newHome.md Home.md

      - name: Create project pages
        run: |
          # create new project index page
          echo "Deployments by environment:" > ${{ env.projectName }}_Home.md
          echo "* [Dev](https://github.com/bromba-noesis/wiki/wiki/${{ env.projectName }}_Development_Deployments)" >> ${{ env.projectName }}_Home.md
          echo "* [Qua](https://github.com/bromba-noesis/wiki/wiki/${{ env.projectName }}_Quality_Deployments)" >> ${{ env.projectName }}_Home.md
          echo "* [Prd](https://github.com/bromba-noesis/wiki/wiki/${{ env.projectName }}_Production_Deployments)" >> ${{ env.projectName }}_Home.md
          # create empty page for each environment 
          echo "-" > ${{ env.projectName }}_Development_Deployments.md
          echo "-" > ${{ env.projectName }}_Quality_Deployments.md
          echo "-" > ${{ env.projectName }}_Production_Deployments.md

      - name: Upload all pages to wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: .
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.bromba_noesis_pat_wiki }}
