name: Wiki project

on: 
    workflow_call:
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: setup
        id: setup 
        run: |
          echo "myDate=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "myHour=$(date +'%H:%M:%S')" >> $GITHUB_OUTPUT
          echo "myCID=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "myBranch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          echo "myTag=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
      
      - name: Update project deployment page
        uses: DamianReeves/write-file-action@master
        with:
          path: Development_Deployments.md
          contents: |
            | Date | Hour | Commit ID | Branch | Tag |
            |------|------|-----------|--------|-----|
            | ${{ steps.setup.outputs.myDate }} | ${{ steps.setup.outputs.myHour }} | ${{ steps.setup.outputs.myCID }} | ${{ steps.setup.outputs.myBranch }} | ${{ steps.setup.outputs.myTag }} |
          write-mode: overwrite

      - name: Upload to wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: .
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.bromba_noesis_pat_wiki }}
