name: Wiki home update

on: 
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup variables
        run: echo "myProject=ccc" >> $GITHUB_ENV

      - name: Checkout wiki repo
        uses: actions/checkout@v3
        with:
          repository: '${{ github.repository }}.wiki'
          sparse-checkout: 'Home.md'

      - name: temp1
        run: |
            find .
            cat Home.md

      - name: Update project wiki files
        #uses: DamianReeves/write-file-action@master
        #with:
        #  path: Home.md
        #  contents: |
        #  write-mode: append
        run: |
          echo * >> Home.md
          echo * [${{ env.myProject }}](https://github.com/bromba-noesis/wiki/wiki/${{ env.myProject }}) >> Home.md

      - name: temp2
        run: |
            cat Home.md
            
      - name: Upload to wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: .
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.bromba_noesis_pat_wiki }}
