name: Wiki project

on: 
    workflow_call:
      inputs:
        projectName:
          required: true
          type: string
        deploymentEnvironment:
          required: true
          type: string
        deploymentDate:
          required: true
          type: string
        deploymentHour:
          required: true
          type: string
        CID:
          required: true
          type: string
        projectBranch:
          required: true
          type: string
        projectTag:
          required: true
          type: string  
    workflow_dispatch:
      inputs:
        projectName:
          required: true
          type: string
        deploymentEnvironment:
          required: true
          type: string
        deploymentDate:
          required: true
          type: string
        deploymentHour:
          required: true
          type: string
        CID:
          required: true
          type: string
        projectBranch:
          required: true
          type: string
        projectTag:
          required: true
          type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Update project deployment page
        uses: DamianReeves/write-file-action@master
        with:
          path: ${{ inputs.projectName }}_${{ inputs.deploymentEnvironment }}_Deployments.md
          contents: |
            | Date | Hour | Commit ID | Branch | Tag |
            |------|------|-----------|--------|-----|
            | ${{ inputs.deploymentDate }} | ${{ inputs.deploymentHour }} | ${{ inputs.CID }} | ${{ inputs.projectBranch }} | ${{ inputs.projectTag }} |
          write-mode: overwrite

      - name: Upload to wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: .
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.bromba_noesis_pat_wiki }}
