name: Wiki home update

on: 
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup variables
        run: echo "myProject=aaa" >> $GITHUB_ENV

      - name: Checkout wiki repo
        uses: actions/checkout@v3
        with:
          repository: '${{ github.repository }}.wiki'
          sparse-checkout: 'Home.md'

      - name: temp1
        run: |
            cat Home.md

      - name: Update project wiki files
        run: |
          # add project to general index page
          echo "* [${{ env.myProject }}](https://github.com/bromba-noesis/wiki/wiki/${{ env.myProject }})" >> Home.md
          # sort index
          grep -v '^[[:space:]]*$' Home.md | sort > newHome.md
          mv newHome.md Home.md
          # create new project index page
          mkdir ${{ env.myProject }}
          echo "Deployments by environment:" > ${{ env.myProject }}/Home.md
          echo "* [Dev](https://github.com/bromba-noesis/envs-public/wiki/Dev-deployments)"
          echo "* [Qua](https://github.com/bromba-noesis/envs-public/wiki/Qua-deployments)"
          echo "* [Prd](https://github.com/bromba-noesis/envs-public/wiki/Prd-deployments)"
          # create empty page for each environment 
          touch ${{ env.myProject }}/Dev-deployments.md
          touch ${{ env.myProject }}/Qua-deployments.md
          touch ${{ env.myProject }}/Prd-deployments.md

      - name: temp2
        run: |
            find .
            cat Home.md
            
      - name: Upload to wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: .
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.bromba_noesis_pat_wiki }}
