name: Wiki

on: 
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup variables
        run: |
          echo "myFile=envs-public/Dev-deployments.md" >> $GITHUB_ENV
          echo "myDate=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "myHour=$(date +'%H:%M:%S')" >> $GITHUB_ENV
          echo "myCID=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "myBranch=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "myTag=${GITHUB_REF_NAME}" >> $GITHUB_ENV
      - name: Checkout entire repo
        uses: actions/checkout@v3
      - name: Update project wiki files
        uses: DamianReeves/write-file-action@master
        with:
          path: ${{ env.myFile }}
          contents: |
            | Date | Hour | Commit ID | Branch | Tag |
            |------|------|-----------|--------|-----|
            | ${{ env.myDate }} | $myHour | env.myCID | env.myBranch | env.myTag |
          write-mode: overwrite  
      - name: Commit  
        run: |
          find .
          cat $myProject/$myEnvironment-deployments.md
          git config --local user.email "test@test.com"
          git config --local user.name "bromba-noesis"
          git commit -a -m "'Update to ${myProject} wiki files"
      - name: Push 
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.bromba_noesis_pat_wiki }}
          force: true
      - name: Upload to wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: $myProject
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.bromba_noesis_pat_wiki }}
